environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python36-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python37-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python38-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python39-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      PYTHON: '3.6'
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      PYTHON: '3.7'
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      PYTHON: '3.8'
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      PYTHON: '3.9'

stack: python %PYTHON% # Sets the Python version on Linux

init:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - pip --version

install:
  - SET SCIPOPTDIR=C:\scipoptdir
  - ps: wget http://scip.zib.de/download/release/SCIPOptSuite-8.0.0-win64-VS15.exe -O scipopt-installer.exe
  - scipopt-installer.exe /S /D=%SCIPOPTDIR%
  - set PATH=%SCIPOPTDIR%\bin;%PATH%

before_build:
  - pip3 install virtualenv
  - virtualenv env
  - env\Scripts\activate
  - python --version
  - pip --version
  - pip install -r requirements.txt

build_script:
  - python assignment02-a.py
  - python assignment02-c.py

for:
-
  matrix:
    only:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

  init:
  - python --version
  - pip --version
  install:
  - wget http://scip.zib.de/download/release/SCIPOptSuite-8.0.0-Linux.deb -O scipopt-installer.deb
  - sudo apt install -y ./scipopt-installer.deb
  before_build:
  - pip3 install virtualenv
  - virtualenv env -p python3
  - source env/bin/activate
  - python --version
  - pip --version
  - pip install -r requirements.txt
