language: python
dist: xenial
sudo: true

before_install:
  - export VERSION=5.0.1
  - pushd .
  - wget http://scip.zib.de/download/release/scipoptsuite-$VERSION.tgz
  - tar xf scipoptsuite-$VERSION.tgz
  - cd scipoptsuite-$VERSION
  - mkdir build && cd build
  - cmake -DSHARED=on -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/travis/.local/ ..
  - make -j4
  - make install
  - popd
  - rm -rf scipoptsuite-$VERSION

script:
  - python --version
  - python assignment02-a.py
  - python assignment02-c.py

matrix:
  include:
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
  - os: osx
    osx_image: xcode9.3
    language: generic
    before_install:
      - export VERSION=5.0.1
      - pushd .
      - wget http://scip.zib.de/download/release/scipoptsuite-$VERSION.tgz
      - tar xf scipoptsuite-$VERSION.tgz
      - cd scipoptsuite-$VERSION
      - mkdir build && cd build
      - cmake -DSHARED=on -DCMAKE_BUILD_TYPE=Release ..
      - make -j2
      - make install
      - popd
      - rm -rf scipoptsuite-$VERSION
      - brew update
      - brew upgrade python3
      - virtualenv env -p python3
      - source env/bin/activate
      - pip install -r requirements.txt
