os: linux
dist: bionic

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'pypy3'

before_install:
  - export SCIPOPTDIR=~/scipoptdir
  - export VERSION=7.0.1
  - pushd .
  - wget http://scip.zib.de/download/release/scipoptsuite-$VERSION.tgz
  - tar xf scipoptsuite-$VERSION.tgz
  - cd scipoptsuite-$VERSION
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$SCIPOPTDIR ..
  - make -j2
  - make install
  - popd
  - rm -rf scipoptsuite-$VERSION

script:
  - python assignment02-a.py
  - python assignment02-c.py

jobs:
  include:
  - os: osx
    osx_image: xcode11.3
    language: generic # python is not supported on OSX builds yet
    install: # this would be done by default if we could pick python as the config language
      - pip3 install virtualenv
      - virtualenv env -p python3
      - source env/bin/activate
      - python --version
      - pip --version
      - pip install -r requirements.txt
      - export DYLD_LIBRARY_PATH=$SCIPOPTDIR/lib:$DYLD_LIBRARY_PATH # this seems to be needed