os: linux
dist: xenial
sudo: true

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - pypy3.5

before_install:
  - export SCIPOPTDIR=~/scipoptdir
  - export VERSION=6.0.0
  - pushd .
  - wget http://scip.zib.de/download/release/scipoptsuite-$VERSION.tgz
  - tar xf scipoptsuite-$VERSION.tgz
  - cd scipoptsuite-$VERSION
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$SCIPOPTDIR ..
  - make -j2
  - make install
  - popd
  - rm -rf scipoptsuite-$VERSION

script:
  - python assignment02-a.py
  - python assignment02-c.py

matrix:
  include:
  - os: osx
    osx_image: xcode10
    language: generic # python is not well supported on OSX builds yet
    python: 3.7 # python is not well supported on OSX builds yet
    before_install:
      - export VERSION=6.0.0
      - pushd .
      - wget http://scip.zib.de/download/release/scipoptsuite-$VERSION.tgz
      - tar xf scipoptsuite-$VERSION.tgz
      - cd scipoptsuite-$VERSION
      - mkdir build && cd build
      - cmake ..
      - make -j2
      - make install
      - popd
      - rm -rf scipoptsuite-$VERSION
    install: # this would be done by default if we could pick python as the config language
      - pip3 install virtualenv
      - virtualenv env -p python3
      - source env/bin/activate
      - python --version
      - pip --version
      - pip install -r requirements.txt
