environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python35-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python36-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python37-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

stack: python 3.7

init:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - pip --version

install:
  - SET SCIPOPTDIR=C:\scipoptdir
  - ps: wget http://scip.zib.de/download/release/SCIPOptSuite-6.0.0-win64-VS15.exe -O scipopt-installer.exe
  - scipopt-installer.exe /S /D=%SCIPOPTDIR%
  - set PATH=%SCIPOPTDIR%\bin;%PATH%

before_build:
  - pip3 install virtualenv
  - virtualenv env
  - env\Scripts\activate
  - python --version
  - pip --version
  - pip install -r requirements.txt

build_script:
  - python assignment02-a.py
  - python assignment02-c.py

for:
-
  matrix:
    only:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

  init:
  - python --version
  - pip --version
  install:
  - wget http://scip.zib.de/download/release/SCIPOptSuite-6.0.0-Linux.deb -O scipopt-installer.deb
  - sudo apt-get install libblas-common libblas3 libgfortran3 liblapack3 -y
  - sudo dpkg -i scipopt-installer.deb
  before_build:
  - pip3 install virtualenv
  - virtualenv env -p python3
  - source env/bin/activate
  - python --version
  - pip --version
  - pip install -r requirements.txt
